steps:
  # Step 1: Set up environment variables
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args: 
      - '-c'
      - |
        echo "export APP_KEY=your_app_key" >> $BASH_ENV
        echo "export APP_ENV=production" >> $BASH_ENV
        echo "export APP_DEBUG=false" >> $BASH_ENV
        echo "export APP_URL=your_app_url" >> $BASH_ENV
        source $BASH_ENV
        
  # Step 2: Checkout the source code
  - name: 'gcr.io/cloud-builders/git'
    args: ['clone', '--depth=1', 'https://github.com/mihairazvan9/web-dev-contact.git', '.']

  # Step 3: Install Composer dependencies
  - name: 'gcr.io/cloud-builders/composer'
    args: ['install', '--ignore-platform-reqs']

  # Step 4: Build assets (if needed)
  - name: 'gcr.io/cloud-builders/php'
    entrypoint: 'php'
    args: ['artisan', 'config:cache']

  # Step 5: Deploy to Google App Engine (adjust as per your deployment needs)
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['app', 'deploy', 'app.yaml']