# steps:
#   - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
#     entrypoint: 'bash'
#     args:
#       - '-c'
#       - |
#         gcloud config set app/cloud_build_timeout 3600 \
#         && gcloud app deploy -q --promote -v=$BUILD_ID \
#         --project=$PROJECT_ID

# timeout: '3600s'
steps:
  # Step 1: Set up environment variables
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args: 
      - '-c'
      - |
        gcloud config set app/cloud_build_timeout 3600 \
        && gcloud app deploy -q --promote -v=$BUILD_ID \
        --project=$PROJECT_ID
        
  # Step 2: Checkout the source code
  - name: 'gcr.io/cloud-builders/git'
    args: ['clone', '--depth=1', 'https://github.com/mihairazvan9/web-dev-contact.git', '.']

  # Step 3: Install Composer dependencies
  - name: 'gcr.io/cloud-builders/composer'
    args: ['install', '--ignore-platform-reqs']

  # Step 4: Build assets (if needed)
  - name: 'gcr.io/cloud-builders/php'
    entrypoint: 'php'
    args: ['artisan', 'config:cache']

  # Step 5: Deploy to Google App Engine (adjust as per your deployment needs)
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['app', 'deploy', 'app.yaml']